from tkinter import *


def click(event):
    global value1
    text = event.widget.cget("text")
    print(text)
    if text == "=":
        if value1.get().isdigit():
            value = int(value1.get())
    elif text == "C":
        value1.set("")
        screen.update()
    else:

        value1.set(value1.get() + text)
        screen.update()
        value = eval(screen.get())
    value1.set(value)
    screen.update()


root = Tk()
root.geometry("300x300")
root.title('A Simple Calculator')
value1 = StringVar()
value1.set("")
screen = Entry(root, textvar=value1)
screen.pack(fill=X, ipadx=30, padx=10, pady=10)
fr1 = Frame(root, bg='black')


b1 = Button(fr1, text="9", padx=20, pady=5, font="Lucida 30")
b1.bind("<Button-1>", click)
b1.pack(side=LEFT, padx=5, pady=5)
b1.bind("<Button-1>", click)
b1 = Button(fr1, text="8", padx=20, pady=5, font="Lucida 30")
b1.bind("<Button-1>", click)
b1.pack(side=LEFT, padx=5, pady=5)
b1 = Button(fr1, text="7", padx=20, pady=5, font="Lucida 30")
b1.pack(side=LEFT, padx=5, pady=5)
b1.bind("<Button-1>", click)
fr1.pack()
fr1 = Frame(root, bg='black')
b1 = Button(fr1, text="6", padx=20, pady=5, font="Lucida 30")
b1.bind("<Button-1>", click)
b1.pack(side=LEFT, padx=5, pady=5)
b1.bind("<Button-1>", click)
b1 = Button(fr1, text="5", padx=20, pady=5, font="Lucida 30")
b1.bind("<Button-1>", click)
b1.pack(side=LEFT, padx=5, pady=5)
b1 = Button(fr1, text="4", padx=20, pady=5, font="Lucida 30")
b1.pack(side=LEFT, padx=5, pady=5)
b1.bind("<Button-1>", click)
fr1.pack()
fr1 = Frame(root, bg='black')
b1 = Button(fr1, text="3", padx=20, pady=20, font="Lucida 30")
b1.bind("<Button-1>", click)
b1.pack(side=LEFT, padx=5, pady=5)
b1.bind("<Button-1>", click)
b1 = Button(fr1, text="2", padx=20, pady=20, font="Lucida 30")
b1.bind("<Button-1>", click)
b1.pack(side=LEFT, padx=5, pady=5)
b1 = Button(fr1, text="1", padx=20, pady=20, font="Lucida 30")
b1.pack(side=LEFT, padx=5, pady=5)
b1.bind("<Button-1>", click)
fr1.pack()
fr1 = Frame(root, bg='black', padx=5, pady=5)
b1 = Button(fr1, text="0", padx=20, pady=20, font="Lucida 30")
b1.bind("<Button-1>", click)
b1.pack(side=LEFT, padx=5)
b1.bind("<Button-1>", click)
b1 = Button(fr1, text="-", padx=20, pady=20, font="Lucida 30")
b1.bind("<Button-1>", click)
b1.pack(side=LEFT, padx=5, pady=5)
b1 = Button(fr1, text="*", padx=20, pady=20, font="Lucida 30")
b1.pack(side=LEFT, padx=20, pady=20)
b1.bind("<Button-1>", click)
fr1.pack()
fr1 = Frame(root, bg='black')
b1 = Button(fr1, text="/", padx=20, pady=20, font="Lucida 30")
b1.bind("<Button-1>", click)
b1.pack(side=LEFT, padx=5, pady=5)
b1.bind("<Button-1>", click)
b1 = Button(fr1, text="%", padx=20, pady=20, font="Lucida 30")
b1.bind("<Button-1>", click)
b1.pack(side=LEFT, padx=5, pady=5)
b1 = Button(fr1, text="=", padx=20, pady=20, font="Lucida 30")
b1.pack(side=LEFT, padx=5, pady=5)
b1.bind("<Button-1>", click)
fr1.pack()
fr1 = Frame(root, bg='black')
b1 = Button(fr1, text="C", padx=20, pady=20, font="Lucida 30")
b1.bind("<Button-1>", click)
b1.pack(side=LEFT, padx=5, pady=5)
b1.bind("<Button-1>", click)
b1 = Button(fr1, text="+", padx=20, pady=20, font="Lucida 30")
b1.bind("<Button-1>", click)
b1.pack(side=LEFT, padx=5, pady=5)
b1 = Button(fr1, text="X", padx=20, pady=20, font="Lucida 30")
b1.pack(side=LEFT, padx=5, pady=5)
b1.bind("<Button-1>", click)
fr1.pack()
root.mainloop()
